from flask import Flask, request, jsonify
import cloudscraper
import requests
import json
import re
import time
import os
import sys
from datetime import datetime
from http.cookiejar import MozillaCookieJar
import io

app = Flask(__name__)

# Your saved cookies as a string
COOKIE_STRING = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
iteraplay.com	FALSE	/	FALSE	1818944207	remember_me	yes
.iteraplay.com	TRUE	/	FALSE	1818944242	_ga_NFYSD8YZN4	GS2.1.s1784384135$o1$g1$t1784384242$j27$l0$h0
#HttpOnly_iteraplay.com	FALSE	/	TRUE	1784384361	__secure_token	eyJ1aWQiOm51bGwsInNpZCI6ImU5ZmEwNjlhNmI1MTczZWM4MDdlMDE3OWFhZDU3OWI2IiwidCI6MTc4NDM4NDI0MjgwNSwibiI6IjEwODAwZmM3YzAyYzgyY2MifTo6MzI2ZWYwMDQzZTZhYTBjNmNlODhiNmFkYmUxNWYyZTFmYjkwZTlmMzQ5MjBhZTdhM2EzNWM3ZGRiNzQ1OTQ2NQ%3D%3D
.iteraplay.com	TRUE	/	FALSE	1818944242	_ga	GA1.1.558453591.1784384135
.iteraplay.com	TRUE	/	FALSE	1818080136	FCCDCF	%5Bnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C%5B%5B32%2C%22%5B%5C%2289fec263-4582-4899-93f3-f98160446051%5C%22%2C%5B1784384136%5D%5D%22%5D%5D%5D
.iteraplay.com	TRUE	/	FALSE	1815920140	FCNEC	%5B%5B%22AKsRol9TLkQ2UJYcRn72sbYVFRmdKbj829okOONU4bmrqE7zgWJ2NTFKjqoruvwlXaLVyxHLmc24a6XID7ZXSq0aYe2L80agFHmQnep_15x9iuo9X8OGAv5DI3VYIbqeAU6EGyGY7oUBnBMu2rDFNu3KwGY8QYGdwA%3D%3D%22%5D%2Cnull%2C%5B%5B21%2C%22%5B%5B%5B%5B5%2C1%2C%5B0%5D%5D%2C%5B1784384138%2C145374000%5D%2C%5B1209600%5D%5D%5D%5D%22%5D%5D%5D
#HttpOnly_iteraplay.com	FALSE	/	TRUE	1818944207	login_token	f0f7cf11ab5adeb1d35cce1df4d0692e383c87d89bc1798edc92b73dd266499181b73aaa48a406d2350abbcd204b2ebc5e24d34613b1e991fe57863667fa25cb
#HttpOnly_iteraplay.com	FALSE	/	TRUE	1784470534	session_id	e9fa069a6b5173ec807e0179aad579b6"""

def load_cookies():
    """Load cookies from the saved string - Vercel compatible"""
    try:
        # Create a cookie jar and load from string
        cookie_jar = MozillaCookieJar()
        
        # Use StringIO instead of tempfile for Vercel
        cookie_file = io.StringIO(COOKIE_STRING)
        cookie_jar.load(cookie_file, ignore_expires=True, ignore_discard=True)
        
        return cookie_jar
    except Exception as e:
        print(f"Failed to load cookies: {e}")
        return None

def get_verification_token(scraper, base_url):
    """Visit the page to get verification token"""
    try:
        response = scraper.get(base_url, timeout=15)
        
        # Check for XSRF token in cookies
        for cookie in scraper.cookies:
            if 'xsrf' in cookie.name.lower() or 'csrf' in cookie.name.lower() or 'token' in cookie.name.lower():
                return cookie.value
        
        # Look for token in HTML
        token_patterns = [
            r'name="csrf-token" content="([^"]+)"',
            r'name="csrf_token" value="([^"]+)"',
            r'"csrfToken":"([^"]+)"',
            r'x-csrf-token: ([^\s]+)',
            r'data-csrf="([^"]+)"',
            r'__csrf_token[:\s]+"([^"]+)"'
        ]
        
        for pattern in token_patterns:
            match = re.search(pattern, response.text)
            if match:
                return match.group(1)
        
        return None
    except Exception as e:
        print(f"Failed to get verification token: {e}")
        return None

def get_stream_data(terabox_url):
    """Get stream data using saved cookies and verification token"""
    base_url = "https://iteraplay.com"
    
    headers = {
        'authority': 'iteraplay.com',
        'accept': '*/*',
        'accept-language': 'en-MM,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
        'content-type': 'application/json',
        'origin': 'https://iteraplay.com',
        'referer': 'https://iteraplay.com/',
        'sec-ch-ua': '"Chromium";v="137", "Not/A)Brand";v="24"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36'
    }
    
    try:
        # Load cookies
        cookie_jar = load_cookies()
        if not cookie_jar:
            return None, "Failed to load cookies"
        
        # Create scraper with cookies
        scraper = cloudscraper.create_scraper(
            browser={
                'browser': 'chrome',
                'platform': 'android',
                'mobile': True,
                'desktop': False
            },
            interpreter='python'
        )
        
        # Set cookies - convert to dict for requests
        cookie_dict = {}
        for cookie in cookie_jar:
            cookie_dict[cookie.name] = cookie.value
        
        # Also set the cookies directly in the session
        scraper.cookies.update(cookie_dict)
        
        # First, visit the page to get verification token
        csrf_token = get_verification_token(scraper, base_url)
        
        # If we found a token, add it to headers
        if csrf_token:
            headers['x-csrf-token'] = csrf_token
            headers['csrf-token'] = csrf_token
            headers['X-XSRF-TOKEN'] = csrf_token
            headers['X-CSRF-Token'] = csrf_token
        
        # Also add the token as a cookie
        if csrf_token:
            scraper.cookies.set('XSRF-TOKEN', csrf_token)
            scraper.cookies.set('csrf_token', csrf_token)
        
        # Make request with cookies and token
        payload = {"url": terabox_url}
        response = scraper.post(
            f"{base_url}/api/stream",
            headers=headers,
            json=payload,
            timeout=30
        )
        
        if response.status_code == 200:
            data = response.json()
            if data.get('status') == 'success':
                return data, None
            else:
                return None, f"API error: {data.get('error', 'Unknown')}"
        elif response.status_code == 429:
            return None, "Rate limited! Try again later"
        elif response.status_code == 403:
            return None, "403 Forbidden - Session may have expired"
        else:
            return None, f"Failed: {response.status_code} - {response.text[:100]}"
            
    except Exception as e:
        return None, f"Error: {str(e)}"

@app.route('/api/terabox', methods=['GET', 'POST'])
def terabox_api():
    """Main API endpoint - Uses saved session cookies to bypass rate limits"""
    if request.method == 'GET':
        url = request.args.get('url')
    else:
        data = request.get_json() or {}
        url = data.get('url')
    
    if not url:
        return jsonify({
            'success': False,
            'error': 'Missing url parameter',
            'message': 'Please provide a terabox URL'
        }), 400
    
    # Auto-add https if missing
    if not url.startswith('http'):
        url = 'https://' + url
    
    # Get stream data using session cookies
    data, error = get_stream_data(url)
    
    if not data:
        return jsonify({
            'success': False,
            'error': 'Failed to get tokens',
            'message': error
        }), 500
    
    file_info = data['list'][0] if data.get('list') else {}
    
    response = {
        'success': True,
        'data': {
            'video_info': {
                'title': file_info.get('name', 'N/A'),
                'size': file_info.get('size_formatted', 'N/A'),
                'size_bytes': file_info.get('size', 0),
                'duration': file_info.get('duration', 'N/A'),
                'quality': file_info.get('quality', 'N/A'),
                'type': file_info.get('type', 'N/A')
            },
            'download_links': {
                'direct_download': file_info.get('normal_dlink'),
                'stream_url': file_info.get('stream_url'),
                'thumbnail': file_info.get('thumbnail')
            }
        },
        'developer': '@KindCoders'
    }
    
    return jsonify(response), 200

@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({
        'status': 'ok',
        'message': 'Terabox API is running - Uses session cookies to bypass rate limits',
        'developer': '@KindCoders'
    }), 200

@app.route('/', methods=['GET'])
def index():
    return jsonify({
        'service': 'Terabox API - Session Cookie Bypass',
        'version': '1.0.0',
        'developer': '@KindCoders',
        'description': 'Uses saved session cookies to bypass rate limiting',
        'endpoints': {
            '/api/terabox': {
                'method': 'POST or GET',
                'params': {
                    'url': 'Terabox share URL (required) - Any format accepted'
                },
                'example_get': '/api/terabox?url=https://terafileshare.com/s/1xJtL3j2LJ-ZsUA6zbG7Pug',
                'example_post': '{"url": "https://terafileshare.com/s/1xJtL3j2LJ-ZsUA6zbG7Pug"}'
            },
            '/api/health': {
                'method': 'GET',
                'description': 'Health check'
            }
        },
        'response': {
            'video_info': 'Title, Size, Duration, Quality, Type',
            'download_links': 'Direct Download, Stream URL, Thumbnail'
        },
        'note': 'No proxy needed - uses saved session cookies'
    }), 200

app = app

if __name__ == '__main__':
    print("=" * 50)
    print("  🎬 TERABOX API - Session Cookie Bypass")
    print("  👨‍💻 Developer: @KindCoders")
    print("=" * 50)
    print("\n📍 Endpoints:")
    print("   GET/POST /api/terabox?url=TERABOX_URL")
    print("   GET /api/health")
    print("   GET / - Documentation")
    print("\n🔧 Starting server...")
    print("=" * 50)
    
    app.run(host='0.0.0.0', port=5000, debug=True)
